import { Providers } from "./providers";
import { Navbar, Footer } from "@/components";
export const metadata = {
  title: "Moment-Image-Sharing-App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Navbar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
